name: IITM Assignment Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  assignment-job:
    runs-on: ubuntu-latest
    steps:
      - name: 24f3004529@ds.study.iitm.ac.in
        run: echo "GitHub Action completed successfully!"
